steps:
  # install dependencies
  - id: install-dependencies
    name: node
    entrypoint: yarn
    args: ['install']
    env:
    - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'

  # run cypress
  - id: yarn run cypress
    name: cypress/included:7.0.1
    entrypoint: yarn
    args: ['run', 'vue-cli-service', 'test:integration', '--headless']
    env:
    - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'
