steps:
  # install dependencies
  - id: install-dependencies
    name: node
    entrypoint: yarn
    args: ['install']
    env:
    - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'

 # run cypress
  - id: run-cypress
    name: cypress/included:7.0.1
    entrypoint: yarn
    args: ['run','cy:report','--headless']
    env:
    - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'
